/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mmorpg.mngment;

import java.util.Collection;
import java.util.Random;
import mmorpg.Characters;
import mmorpg.Helper;
import mmorpg.Users;
import mmorpg.mngment.UserMng;

/**
 *
 * @author heszar
 */
public class CharacterMng extends javax.swing.JFrame {

    /**
     * Creates new form CharacterMng
     */
    public CharacterMng() {
        initComponents();
    }
    
    private Users loggedInUser = null;
    public void setLoggedInUser(Users loggedInUser)
    {
        this.loggedInUser = loggedInUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_userMng = new javax.swing.JButton();
        txt_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cb_class = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cb_race = new javax.swing.JComboBox();
        btn_createCharacter = new javax.swing.JButton();
        cb_characters = new javax.swing.JComboBox();
        btn_getcharacter = new javax.swing.JButton();
        lbl_name = new javax.swing.JLabel();
        lbl_class = new javax.swing.JLabel();
        lbl_race = new javax.swing.JLabel();
        lbl_level = new javax.swing.JLabel();
        lbl_createCharError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Character Managment YeeeeeeeY!");

        btn_userMng.setText("User Managment pls");
        btn_userMng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_userMngMouseClicked(evt);
            }
        });
        btn_userMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userMngActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jLabel3.setText("CLass");

        cb_class.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Warrior", "Hunter", "Mage", "Priest", "Warlock" }));

        jLabel4.setText("Race");

        cb_race.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Human", "Orc", "Dwarf", "Elf", "Gnome", "Undead" }));

        btn_createCharacter.setText("Create Character");
        btn_createCharacter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_createCharacterMouseClicked(evt);
            }
        });

        cb_characters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_charactersMouseClicked(evt);
            }
        });
        cb_characters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_charactersActionPerformed(evt);
            }
        });

        btn_getcharacter.setText("Get character");
        btn_getcharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getcharacterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_createCharacter)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(btn_userMng))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel1)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_name)
                                        .addComponent(cb_class, 0, 95, Short.MAX_VALUE)
                                        .addComponent(cb_race, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_createCharError)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cb_characters, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_getcharacter))
                    .addComponent(lbl_name)
                    .addComponent(lbl_class)
                    .addComponent(lbl_race)
                    .addComponent(lbl_level))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cb_characters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_getcharacter))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cb_class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cb_race, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_createCharacter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(lbl_createCharError)
                        .addGap(28, 28, 28)
                        .addComponent(btn_userMng)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lbl_name)
                        .addGap(7, 7, 7)
                        .addComponent(lbl_class)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_race)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_level)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_userMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userMngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_userMngActionPerformed

    private void btn_userMngMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_userMngMouseClicked
        
        UserMng mngPanel = new UserMng();
        mngPanel.setLoggedInUser(loggedInUser);
        mngPanel.UpdateUserValues();
        
        this.setVisible(false);
        mngPanel.setVisible(true);
    }//GEN-LAST:event_btn_userMngMouseClicked

    private void btn_createCharacterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_createCharacterMouseClicked
        // TODO add your handling code here:
        txt_name.setText("");
        if(loggedInUser == null)
        {
            lbl_createCharError.setText("No logged in user found");
            return;
        }
        
        if("".equals(txt_name.getText()))
        {
            lbl_createCharError.setText("Fill in all the forms please");
            return;
        }
        
        Helper help = new Helper();
        Characters character = help.ReadCharacter(txt_name.getText());

        if(character != null)
        {
            lbl_createCharError.setText("Name allready exists");
            return;
        }
        
        int slots = loggedInUser.getCharacterSlots();
        
        if(slots <= 0)
        {
            lbl_createCharError.setText("Not enough slots for a new character");
            return;
        }
        
        String race = String.valueOf(cb_race.getSelectedItem());
        String className = String.valueOf(cb_class.getSelectedItem());
        Random rand = new Random();

        int level = rand.nextInt(100) + 1;
        
        Characters newChar = new Characters(txt_name.getText(), className, race, level);
        help.CreateCharacter(newChar, loggedInUser.getUserName());
        help.removeCharSlot(loggedInUser);
        
        setLoggedInUser(help.ReadUsers(loggedInUser.getUserName()));
        lbl_createCharError.setText("Succes!");
        
    }//GEN-LAST:event_btn_createCharacterMouseClicked

    private void btn_getcharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getcharacterActionPerformed
        // TODO add your handling code here:
        if(loggedInUser == null)
            return;
        
        String selectedValue = String.valueOf(cb_characters.getSelectedItem());
        
        Helper help = new Helper();
        Characters character = help.ReadCharacter(selectedValue);
        
        lbl_name.setText(character.getName());
        lbl_class.setText(character.getClass1());
        lbl_race.setText(character.getRace());
        lbl_level.setText(String.valueOf(character.getLevel()));
        
        
    }//GEN-LAST:event_btn_getcharacterActionPerformed

    private void cb_charactersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_charactersActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cb_charactersActionPerformed

    private void cb_charactersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_charactersMouseClicked
        // TODO add your handling code here:
        if(loggedInUser == null)
            return;
        
        Helper help = new Helper();
        Collection<Characters> characternames = help.getAllCharactersByUsername(loggedInUser.getUserName());
        
        for(Characters characterName : characternames)
        cb_characters.addItem(characterName);
    }//GEN-LAST:event_cb_charactersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharacterMng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharacterMng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharacterMng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharacterMng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharacterMng().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_createCharacter;
    private javax.swing.JButton btn_getcharacter;
    private javax.swing.JButton btn_userMng;
    private javax.swing.JComboBox cb_characters;
    private javax.swing.JComboBox cb_class;
    private javax.swing.JComboBox cb_race;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_class;
    private javax.swing.JLabel lbl_createCharError;
    private javax.swing.JLabel lbl_level;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_race;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
