/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mmorpg.mngment;

import mmorpg.Helper;
import mmorpg.Users;

/**
 *
 * @author heszar
 */
public class UserMng extends javax.swing.JFrame {

    /**
     * Creates new form UserMng
     */
    public UserMng() {
        initComponents();
    }
    
    public void UpdateUserValues()
    {
        if(loggedInUser != null)
        {
            lbl_currentBalance.setText("Update balance (current: " + loggedInUser.getBalance() + ")");
            lbl_currentSubscription.setText("Subscription (current: " + loggedInUser.getMonthsPayed() + ")");
            lbl_currentSlots.setText("Slots (current: " + loggedInUser.getCharacterSlots() + ")");
        }
    }
    
    private Users loggedInUser = null;
    public void setLoggedInUser(Users loggedInUser)
    {
        this.loggedInUser = loggedInUser;
    }
    
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_charachterMng = new javax.swing.JButton();
        lbl_currentBalance = new javax.swing.JLabel();
        txt_balance = new javax.swing.JTextField();
        btn_update_balance = new javax.swing.JButton();
        lbl_currentSubscription = new javax.swing.JLabel();
        btn_update_subscription = new javax.swing.JButton();
        lbl_currentSlots = new javax.swing.JLabel();
        txt_update_slots = new javax.swing.JTextField();
        btn_update_slots = new javax.swing.JButton();
        lbl_balanceLabel = new javax.swing.JLabel();
        cb_subscription = new javax.swing.JComboBox();
        lbl_subcriptionLabel = new javax.swing.JLabel();
        lbl_slotsLabel = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("User managament yeaah!");

        btn_charachterMng.setText("Character managment");
        btn_charachterMng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_charachterMngMouseClicked(evt);
            }
        });
        btn_charachterMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_charachterMngActionPerformed(evt);
            }
        });

        lbl_currentBalance.setText("Update Balance");

        btn_update_balance.setText("Update");
        btn_update_balance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_update_balanceMouseClicked(evt);
            }
        });

        lbl_currentSubscription.setText("Subscription");

        btn_update_subscription.setText("Update");
        btn_update_subscription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_update_subscriptionMouseClicked(evt);
            }
        });

        lbl_currentSlots.setText("Slots");

        btn_update_slots.setText("Update");
        btn_update_slots.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_update_slotsMouseClicked(evt);
            }
        });

        cb_subscription.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "12" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_currentBalance)
                            .addComponent(lbl_currentSubscription)
                            .addComponent(lbl_currentSlots))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_balance, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                .addComponent(txt_update_slots))
                            .addComponent(cb_subscription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_update_balance)
                            .addComponent(btn_update_subscription)
                            .addComponent(btn_update_slots)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btn_charachterMng, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_balanceLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_subcriptionLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_slotsLabel)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_currentBalance)
                    .addComponent(txt_balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update_balance))
                .addGap(3, 3, 3)
                .addComponent(lbl_balanceLabel)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_currentSubscription)
                    .addComponent(btn_update_subscription)
                    .addComponent(cb_subscription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lbl_subcriptionLabel)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_currentSlots)
                    .addComponent(txt_update_slots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update_slots))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_slotsLabel)
                .addGap(33, 33, 33)
                .addComponent(btn_charachterMng)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_charachterMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_charachterMngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_charachterMngActionPerformed

    private void btn_charachterMngMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_charachterMngMouseClicked
        
        CharacterMng charMngPanel = new CharacterMng();
        charMngPanel.setLoggedInUser(loggedInUser);
        
        this.setVisible(false);
        charMngPanel.setVisible(true);
    }//GEN-LAST:event_btn_charachterMngMouseClicked

    private void btn_update_balanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_update_balanceMouseClicked
        // TODO add your handling code here:
        lbl_balanceLabel.setText("");
        if(loggedInUser == null)
        {
            lbl_balanceLabel.setText("Helaas, er is niemand ingelogd");
            return;
        }
        
        //haal de waarde op die bij de balance toegevoegd moet worden
        String balance = txt_balance.getText();
        //converteer string naar een int
        Integer balanceValue = Integer.parseInt(balance);
        
        Helper help = new Helper();
        help.UpdateUserBalance(loggedInUser,balanceValue);
        setLoggedInUser(help.ReadUsers(loggedInUser.getUserName()));
        
        lbl_balanceLabel.setText("succes!");
        txt_balance.setText("");
        UpdateUserValues();
    }//GEN-LAST:event_btn_update_balanceMouseClicked

    private void btn_update_subscriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_update_subscriptionMouseClicked
        // TODO add your handling code here:
        lbl_subcriptionLabel.setText("");
        if(loggedInUser == null)
        {
            lbl_subcriptionLabel.setText("Helaas, er is niemand ingelogd");
            return;
        }
        
        int balance = loggedInUser.getBalance();
        
        String subscription = String.valueOf(cb_subscription.getSelectedItem());
        int subvalue = Integer.parseInt(subscription);
        int subPrice = 0;
        
        switch(subvalue)
        {
            case 1:
                subPrice = 5;
                break;
            case 2:
                subPrice = 8;
                break;
            case 3:
                subPrice = 10;
                break;
            case 12:
                subPrice = 35;
                break;
                
        }
        
        if(balance < subPrice)
        {
            lbl_subcriptionLabel.setText("Not enough balance in account");
            return;
        }
        else
            balance = balance - subPrice;
        
        Helper help = new Helper();
        help.UpdateSubscription(loggedInUser, subvalue, balance);
        setLoggedInUser(help.ReadUsers(loggedInUser.getUserName()));
        
        lbl_subcriptionLabel.setText("succes!");
        UpdateUserValues();
    }//GEN-LAST:event_btn_update_subscriptionMouseClicked

    private void btn_update_slotsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_update_slotsMouseClicked
        // TODO add your handling code here:
        lbl_slotsLabel.setText("");
        if(loggedInUser == null)
        {
            lbl_balanceLabel.setText("Helaas, er is niemand ingelogd");
            return;
        }
        
        int balance = loggedInUser.getBalance();
        
        //haal de waarde op die bij de slots toegevoegd moet worden
        String slots = txt_update_slots.getText();
        //converteer string naar een int
        int slotsValue = Integer.parseInt(slots);
        
        if(balance < slotsValue)
        {
            lbl_slotsLabel.setText("not enough balance in account");
            return;
        }
        
        Helper help = new Helper();
        help.UpdateUserSlots(loggedInUser,slotsValue);
        setLoggedInUser(help.ReadUsers(loggedInUser.getUserName()));
        
        lbl_slotsLabel.setText("succes!");
        txt_update_slots.setText("");
        UpdateUserValues();
    }//GEN-LAST:event_btn_update_slotsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMng().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_charachterMng;
    private javax.swing.JButton btn_update_balance;
    private javax.swing.JButton btn_update_slots;
    private javax.swing.JButton btn_update_subscription;
    private javax.swing.JComboBox cb_subscription;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_balanceLabel;
    private javax.swing.JLabel lbl_currentBalance;
    private javax.swing.JLabel lbl_currentSlots;
    private javax.swing.JLabel lbl_currentSubscription;
    private javax.swing.JLabel lbl_slotsLabel;
    private javax.swing.JLabel lbl_subcriptionLabel;
    private javax.swing.JTextField txt_balance;
    private javax.swing.JTextField txt_update_slots;
    // End of variables declaration//GEN-END:variables
}
